server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: syncsenta-ai-service
  profiles:
    active: development

# AI Configuration - OpenAI Only for Hedera AI Agent
openai:
  api:
    key: ${OPENAI_API_KEY:sk-temp-placeholder-key}
    base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    model: ${OPENAI_MODEL:gpt-3.5-turbo}
    max-tokens: ${OPENAI_MAX_TOKENS:1500}
    temperature: ${OPENAI_TEMPERATURE:0.7}
    timeout: 30s

# Hedera Network Configuration (Blockchain layer - optional)
hedera:
  network:
    type: ${HEDERA_NETWORK:testnet}
    node-url: ${HEDERA_NODE_URL:https://testnet.mirrornode.hedera.com}
  account:
    id: ${HEDERA_ACCOUNT_ID:#{null}}
    private-key: ${HEDERA_PRIVATE_KEY:#{null}}

# CORS Configuration for React frontend
cors:
  allowed-origins: 
    - http://localhost:5173
    - http://localhost:3000
    - https://syncsenta.netlify.app
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.syncsenta.ai: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ALWAYS

---
# Testnet Profile (Default for development)
spring:
  config:
    activate:
      on-profile: testnet

hedera:
  ai:
    base-url: https://api.testnet.moonscape.hedera.com/v1
  network:
    type: testnet
    node-url: https://testnet.mirrornode.hedera.com

logging:
  level:
    com.syncsenta.ai: DEBUG
    org.springframework.web: INFO

---
# Development Profile (Uses OpenAI as LLM Provider)
spring:
  config:
    activate:
      on-profile: development
  
# Primary LLM configuration for development
openai:
  api:
    key: ${OPENAI_API_KEY:sk-temp-placeholder-key}
    model: ${OPENAI_MODEL:gpt-3.5-turbo}

logging:
  level:
    com.syncsenta.ai: DEBUG
    org.springframework.web: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    com.syncsenta.ai: WARN
    org.springframework.web: WARN
